name: Charity Ops
colors:
  primary: "hsl(171, 100%, 41%)"
  text: "hsl(0, 0%, 4%)"
  link: "hsl(217, 71%, 53%)"
  info: "hsl(204, 86%, 53%)"
  success: "hsl(141, 71%, 48%)"
  warning: "hsl(48, 100%, 67%)"
  danger: "hsl(348, 100%, 61%)"