/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "AppUserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "CommentTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ContactTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "EventTopic": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "FrontendApp": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "GOOGLE_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "IndexStorage": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "IndexingQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "InteractionTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "NoReply": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "UsersTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "WebClient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
  }
}
